'use strict';
const { describe, it, before } = require('node:test');
const assert = require('node:assert/strict');
const { postTool, healthCheck } = require('../helpers/utcp-client');

function resVal(body) { if (body == null) return null; if (typeof body === 'object' && 'result' in body) return body.result; return null; }
async function exec(context, code, args, safety_checks, timeout_ms) {
  const body = { context, code };
  if (args) body.args = args;
  if (safety_checks !== undefined) body.safety_checks = safety_checks;
  if (timeout_ms) body.timeout_ms = timeout_ms;
  const r = await postTool('executeJavascript', body);
  return r;
}

describe('live: executeJavascript — v3.7 component families (N-R)', () => {
  let health;
  before(async () => { health = await healthCheck(); });
  function skip(t) { if (!health || !health.ok) { t.skip(`editor not running: ${health ? health.reason : 'no health'}`); return true; } return false; }
  const CLEAN = 'const sc=cc.director.getScene();const M="__v37_tmp__";for(const n of [...sc.children])if(n.name===M){n.removeFromParent();n.destroy();}';
  function CC(name) { return `(cc["${name}"]||cc.js.getClassByName("cc.${name}")||cc.js.getClassByName("${name}"))`; }

  describe('N UI components', () => {
    it('N1 Label string/fontSize', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + `const Label=${CC('Label')}; if(!Label) return {skip:true}; const n=new cc.Node(M);sc.addChild(n); const lab=n.addComponent(Label); lab.string="WIN"; lab.fontSize=32; const out={s:n.getComponent(Label).string,f:n.getComponent(Label).fontSize}; n.removeFromParent(); n.destroy(); return out;`); assert.equal(r.ok, true); const v = resVal(r.body); assert.ok(v && (v.skip || v.s === 'WIN')); });
    it('N2 RichText (with UITransform)', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + `const RT=${CC('RichText')}; if(!RT) return {skip:true}; const UT=cc.js.getClassByName("cc.UITransform"); const n=new cc.Node(M);sc.addChild(n); if(UT) n.addComponent(UT); const rt=n.addComponent(RT); rt.string="<color=#ff0000>hi</color>"; const s=n.getComponent(RT).string; n.removeFromParent(); n.destroy(); return {s};`); assert.equal(r.ok, true); const v = resVal(r.body); assert.ok(v && (v.skip || !!v.s)); });
    it('N3 Sprite color', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + 'const n=new cc.Node(M);sc.addChild(n); const sp=n.addComponent(cc.Sprite); const c=new cc.Color(10,20,30,255); sp.color=c; const out=[sp.color.r,sp.color.g,sp.color.b]; n.removeFromParent(); n.destroy(); return out;'); assert.equal(r.ok, true); const v = resVal(r.body); assert.equal(v[0], 10); });
    it('N4 Mask type', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + `const Mask=${CC('Mask')}; if(!Mask) return {skip:true}; const n=new cc.Node(M);sc.addChild(n); const m=n.addComponent(Mask); const t=m.type; n.removeFromParent(); n.destroy(); return {type:typeof t};`); assert.equal(r.ok, true); });
    it('N5 Graphics lineWidth + path', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + `const G=${CC('Graphics')}; if(!G) return {skip:true}; const n=new cc.Node(M);sc.addChild(n); const g=n.addComponent(G); g.lineWidth=5; g.moveTo(0,0); g.lineTo(10,10); g.stroke(); const ok=g.lineWidth===5; n.removeFromParent(); n.destroy(); return {ok};`); assert.equal(r.ok, true); });
    it('N6 Layout type', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + `const L=${CC('Layout')}; if(!L) return {skip:true}; const Type=cc.Layout&&cc.Layout.Type; const n=new cc.Node(M);sc.addChild(n); const lo=n.addComponent(L); if(Type) lo.type=Type.HORIZONTAL; const out=lo.type; n.removeFromParent(); n.destroy(); return {out};`); assert.equal(r.ok, true); });
    it('N7 ProgressBar progress', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + `const PB=${CC('ProgressBar')}; if(!PB) return {skip:true}; const n=new cc.Node(M);sc.addChild(n); const pb=n.addComponent(PB); pb.progress=0.75; const v=pb.progress; n.removeFromParent(); n.destroy(); return {v};`); assert.equal(r.ok, true); const v = resVal(r.body); assert.ok(v.skip || Math.abs(v.v - 0.75) < 1e-6); });
    it('N8 Widget align', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + `const W=${CC('Widget')}; if(!W) return {skip:true}; const n=new cc.Node(M);sc.addChild(n); const w=n.addComponent(W); w.isAlignLeft=true; w.left=10; const out={l:w.isAlignLeft,left:w.left}; n.removeFromParent(); n.destroy(); return out;`); assert.equal(r.ok, true); });
    it('N9 UIOpacity', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + `const UO=${CC('UIOpacity')}; if(!UO) return {skip:true}; const n=new cc.Node(M);sc.addChild(n); const uo=n.addComponent(UO); uo.opacity=128; const v=uo.opacity; n.removeFromParent(); n.destroy(); return {v};`); assert.equal(r.ok, true); const v = resVal(r.body); assert.ok(v.skip || v.v === 128); });
    it('N10 UITransform via getClassByName', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + 'const UT=cc.js.getClassByName("cc.UITransform"); if(!UT) return {skip:true}; const n=new cc.Node(M);sc.addChild(n); const ut=n.addComponent(UT); ut.setContentSize(200,100); const out=[ut.contentSize.width,ut.contentSize.height]; n.removeFromParent(); n.destroy(); return out;'); assert.equal(r.ok, true); const v = resVal(r.body); assert.ok(v.skip || (v[0] === 200 && v[1] === 100)); });
  });

  describe('O physics 3D/2D', () => {
    it('O1 RigidBody probe', async (t) => { if (skip(t)) return; const r = await exec('scene', 'return {hasRB:typeof cc.RigidBody!=="undefined"||!!cc.js.getClassByName("cc.RigidBody")||!!cc.physics||typeof cc.PhysicsSystem!=="undefined", hasRBClass:!!cc.js.getClassByName("cc.RigidBody")};'); assert.equal(r.ok, true); });
    it('O2 BoxCollider probe', async (t) => { if (skip(t)) return; const r = await exec('scene', 'return {has:!!cc.js.getClassByName("cc.BoxCollider")||typeof cc.BoxCollider!=="undefined"};'); assert.equal(r.ok, true); });
    it('O3 BoxCollider size', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + 'const BC=cc.js.getClassByName("cc.BoxCollider"); if(!BC) return {skip:true}; const n=new cc.Node(M);sc.addChild(n); const bc=n.addComponent(BC); try{bc.size=new cc.Vec3(1,2,3);}catch(e){} const out=bc.size? [bc.size.x,bc.size.y,bc.size.z]:null; n.removeFromParent(); n.destroy(); return out||{skip:true};'); assert.equal(r.ok, true); const v = resVal(r.body); assert.ok(v.skip || v.length === 3); });
    it('O4 RigidBody2D probe', async (t) => { if (skip(t)) return; const r = await exec('scene', 'return {has:!!cc.js.getClassByName("cc.RigidBody2D")||typeof cc.RigidBody2D!=="undefined"};'); assert.equal(r.ok, true); });
    it('O5 BoxCollider2D probe', async (t) => { if (skip(t)) return; const r = await exec('scene', 'return {has:!!cc.js.getClassByName("cc.BoxCollider2D")||typeof cc.BoxCollider2D!=="undefined"};'); assert.equal(r.ok, true); });
    it('O6 PhysicsSystem enabled', async (t) => { if (skip(t)) return; const r = await exec('scene', 'const ps=cc.director.getPhysicsSystem ? cc.director.getPhysicsSystem() : (cc.PhysicsSystem&&cc.PhysicsSystem.instance); return {has:!!ps, enable: ps? ps.enable : null};'); assert.equal(r.ok, true); });
  });

  describe('P light / camera', () => {
    it('P1 DirectionalLight probe', async (t) => { if (skip(t)) return; const r = await exec('scene', 'return {has:!!cc.js.getClassByName("cc.DirectionalLight")||typeof cc.DirectionalLight!=="undefined"};'); assert.equal(r.ok, true); });
    it('P2 DirectionalLight color/intensity', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + 'const DL=cc.js.getClassByName("cc.DirectionalLight"); if(!DL) return {skip:true}; const n=new cc.Node(M);sc.addChild(n); const dl=n.addComponent(DL); try{dl.color=new cc.Color(255,200,100,255);}catch(e){} try{dl.illuminance=5000;}catch(e){} const out={hasColor:!!dl.color, illum: dl.illuminance}; n.removeFromParent(); n.destroy(); return out;'); assert.equal(r.ok, true); });
    it('P3 SpotLight probe', async (t) => { if (skip(t)) return; const r = await exec('scene', 'return {has:!!cc.js.getClassByName("cc.SpotLight")||typeof cc.SpotLight!=="undefined"};'); assert.equal(r.ok, true); });
    it('P4 Camera fov/near', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + 'const Cam=cc.js.getClassByName("cc.Camera")||cc.Camera; if(!Cam) return {skip:true}; const n=new cc.Node(M);sc.addChild(n); const cam=n.addComponent(Cam); try{cam.fov=60;}catch(e){} try{cam.near=0.1;}catch(e){} const out={fov:cam.fov,near:cam.near}; n.removeFromParent(); n.destroy(); return out;'); assert.equal(r.ok, true); });
  });

  describe('Q audio / particles', () => {
    it('Q1 AudioSource probe', async (t) => { if (skip(t)) return; const r = await exec('scene', 'return {has:!!cc.js.getClassByName("cc.AudioSource")||typeof cc.AudioSource!=="undefined"};'); assert.equal(r.ok, true); });
    it('Q2 AudioSource volume/loop', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + 'const AS=cc.js.getClassByName("cc.AudioSource"); if(!AS) return {skip:true}; const n=new cc.Node(M);sc.addChild(n); const a=n.addComponent(AS); a.volume=0.5; a.loop=false; const out={v:a.volume,loop:a.loop}; n.removeFromParent(); n.destroy(); return out;'); assert.equal(r.ok, true); });
    it('Q3 ParticleSystem probe', async (t) => { if (skip(t)) return; const r = await exec('scene', 'return {has:!!cc.js.getClassByName("cc.ParticleSystem")||typeof cc.ParticleSystem!=="undefined", has2D:!!cc.js.getClassByName("cc.ParticleSystem2D")};'); assert.equal(r.ok, true); });
    it('Q4 ParticleSystem hasDuration', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + 'const PS=cc.js.getClassByName("cc.ParticleSystem")||cc.js.getClassByName("cc.ParticleSystem2D"); if(!PS) return {skip:true}; const n=new cc.Node(M);sc.addChild(n); const ps=n.addComponent(PS); const out={hasDuration: "duration" in ps || "totalParticles" in ps}; n.removeFromParent(); n.destroy(); return out;'); assert.equal(r.ok, true); });
  });

  describe('R animation / spine', () => {
    it('R1 Animation clip list', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + 'const A=cc.js.getClassByName("cc.Animation"); if(!A) return {skip:true}; const n=new cc.Node(M);sc.addChild(n); const anim=n.addComponent(A); const clips=anim.clips||[]; const out={count:clips.length}; n.removeFromParent(); n.destroy(); return out;'); assert.equal(r.ok, true); });
    it('R2 Spine count', async (t) => { if (skip(t)) return; const r = await exec('scene', 'const sc=cc.director.getScene();let n=0;const st=[sc];while(st.length){const x=st.pop();for(const c of x.components||[])if(c.constructor&&c.constructor.name==="Skeleton")n++;for(const c of x.children||[])st.push(c);} return {count:n};'); assert.equal(r.ok, true); assert.ok(typeof resVal(r.body).count === 'number'); });
    it('R3 Spine skeletonData', async (t) => { if (skip(t)) return; const r = await exec('scene', 'const sc=cc.director.getScene();let s=null;const st=[sc];while(st.length&&!s){const x=st.pop();for(const c of x.components||[]){if(c.constructor&&c.constructor.name==="Skeleton"){s={node:x.name,hasData:!!c.skeletonData,anim:c.animation||c.defaultAnimation||null};break;}}for(const c of x.children||[])st.push(c);} return s;'); assert.equal(r.ok, true); });
    it('R4 SkeletalAnimation probe', async (t) => { if (skip(t)) return; const r = await exec('scene', 'return {has:!!cc.js.getClassByName("cc.SkeletalAnimation")||!!cc.js.getClassByName("cc.SkeletonAnimation")};'); assert.equal(r.ok, true); });
    it('R5 bezier + easing', async (t) => { if (skip(t)) return; const r = await exec('scene', 'const b=(p0,p1,p2,p3,t)=>{const u=1-t;return u*u*u*p0+3*u*u*t*p1+3*u*t*t*p2+t*t*t*p3;}; const ease=t=>t*t*(3-2*t); const bez=[b(0,30,70,100,0),b(0,30,70,100,0.5),b(0,30,70,100,1)]; const e=[ease(0),ease(0.5),ease(1)]; return {bez,e};'); assert.equal(r.ok, true); const v = resVal(r.body); assert.equal(v.bez[0], 0); assert.equal(v.bez[2], 100); });
    it('R6 move along bezier', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + 'const n=new cc.Node(M);sc.addChild(n); const b=(p0,p1,p2,p3,t)=>{const u=1-t;return u*u*u*p0+3*u*u*t*p1+3*u*t*t*p2+t*t*t*p3;}; const pts=[]; for(const t of [0,0.5,1]){ n.setPosition(b(0,30,70,100,t), b(0,80,20,100,t), 0); pts.push([Math.round(n.position.x),Math.round(n.position.y)]);} n.removeFromParent(); n.destroy(); return pts;'); assert.equal(r.ok, true); const v = resVal(r.body); assert.equal(v.length, 3); assert.equal(v[2][0], 100); });
  });

  // ── S. Gameplay runtime + deep skeleton (migrated from probe-exec-tween-poll.js / probe-exec-engine-live.js) ──
  describe('S gameplay runtime & skeleton depth', () => {
    it('S1 engine runtime state', async (t) => { if (skip(t)) return; const r = await exec('scene', 'return { paused: cc.game ? !!cc.game.paused : null, timeScale: cc.director && cc.director.getScheduler ? cc.director.getScheduler().getTimeScale() : null, totalFrames: cc.director ? cc.director.totalFrames : null };'); assert.equal(r.ok, true); const v = resVal(r.body); assert.ok(typeof v.timeScale === 'number'); });
    it('S2 resume + setTimeScale read-back', async (t) => { if (skip(t)) return; const r = await exec('scene', 'if(cc.game) cc.game.resume(); if(cc.director && cc.director.getScheduler) cc.director.getScheduler().setTimeScale(1); return { paused: cc.game ? cc.game.paused : null, timeScale: cc.director.getScheduler().getTimeScale() };'); assert.equal(r.ok, true); const v = resVal(r.body); assert.equal(v.timeScale, 1); });
    it('S3 tween start + position poll (gameplay)', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + 'const n=new cc.Node(M); n.setPosition(0,0,0); sc.addChild(n); let regOk=false; try{ cc.tween(n).to(0.5,{position:new cc.Vec3(100,0,0)}).start(); regOk=true; }catch(e){ regOk=false; } const pos=[n.position.x,n.position.y,n.position.z]; n.removeFromParent(); n.destroy(); return {regOk,pos};'); assert.equal(r.ok, true); const v = resVal(r.body); assert.equal(v.regOk, true, 'tween registration'); assert.ok(Array.isArray(v.pos) && v.pos.every(Number.isFinite), 'positions finite'); });
    it('S4 tween over-time trajectory (wait inside scene)', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + 'const n=new cc.Node(M); n.setPosition(0,0,0); sc.addChild(n); try{cc.tween(n).to(0.3,{position:new cc.Vec3(100,0,0)}).start();}catch(e){} const p0=[n.position.x,n.position.y]; await new Promise(res=>setTimeout(res,400)); const p1=[n.position.x,n.position.y]; n.removeFromParent(); n.destroy(); return {p0,p1,moved:Math.abs(p1[0]-p0[0])>0.5};', null, undefined, 5000); assert.equal(r.ok, true); const v = resVal(r.body); assert.deepEqual(v.p0, [0, 0], 'starts at origin'); assert.ok(v.p1.every(Number.isFinite), 'p1 finite'); assert.equal(typeof v.moved, 'boolean'); });
    it('S5 skeleton deep scan (spine/dragonbones/skeletal3d)', async (t) => { if (skip(t)) return; const r = await exec('scene', 'const sc=cc.director.getScene();const found={spine:[],dragonbones:[],skeletal3d:[]};const st=[sc];while(st.length){const n=st.pop();for(const c of n.components||[]){const cls=c&&c.constructor?c.constructor.name:"";const hasBones=!!(c&&(c.skeleton||c._skeleton||c.skeletonData));if(cls==="Skeleton"||cls==="sp.Skeleton"||(c&&c.skeletonData!==undefined))found.spine.push({node:n.name,cls,hasBones});if(cls==="ArmatureDisplay"||cls.indexOf("dragonBones")>=0)found.dragonbones.push({node:n.name,cls});if(cls==="SkeletalAnimation"||cls==="cc.SkeletalAnimation")found.skeletal3d.push({node:n.name,cls});}for(const c of n.children||[])st.push(c);}return found;'); assert.equal(r.ok, true); const v = resVal(r.body); assert.ok(Array.isArray(v.spine) && Array.isArray(v.dragonbones) && Array.isArray(v.skeletal3d)); });
    it('S6 skeleton API reachability', async (t) => { if (skip(t)) return; const r = await exec('scene', 'return { hasSpineSkeleton: typeof (globalThis.sp && sp.Skeleton)!=="undefined", hasSkeletalAnimation: typeof cc.SkeletalAnimation!=="undefined", hasSkinnedMeshRenderer: typeof cc.SkinnedMeshRenderer!=="undefined", hasAnimationController: typeof cc.AnimationController!=="undefined" };'); assert.equal(r.ok, true); const v = resVal(r.body); assert.equal(typeof v.hasSpineSkeleton, 'boolean'); });
    it('S7 node full transform read-back (lookup by name)', async (t) => { if (skip(t)) return; const r = await exec('scene', 'const sc=cc.director.getScene();let tg=null;const st=[sc];while(st.length&&!tg){const n=st.pop();if(n.name===args.name){tg=n;break;}for(const c of n.children||[])st.push(c);} if(!tg) return null; const p=tg.position,s=tg.scale; return {name:tg.name,pos:[p.x,p.y,p.z],scale:[s.x,s.y,s.z],active:tg.active,childCount:tg.children.length,compCount:tg.components.length};', { name: 'Canvas' }); assert.equal(r.ok, true); const v = resVal(r.body); if (v === null) { t.skip('Canvas not present'); return; } assert.ok(v.pos.every(Number.isFinite)); assert.equal(typeof v.childCount, 'number'); });
    it('S8 UITransform anchor read', async (t) => { if (skip(t)) return; const r = await exec('scene', CLEAN + 'const UT=cc.js.getClassByName("cc.UITransform"); if(!UT) return {skip:true}; const n=new cc.Node(M);sc.addChild(n); const ut=n.addComponent(UT); const out={ax:ut.anchorX,ay:ut.anchorY,w:ut.contentSize.width,h:ut.contentSize.height}; n.removeFromParent(); n.destroy(); return out;'); assert.equal(r.ok, true); const v = resVal(r.body); assert.ok(v.skip || (v.ax === 0.5 && v.ay === 0.5), `anchor default 0.5, got ${JSON.stringify(v)}`); });
    it('S9 Vec3/Quat/tween reachability', async (t) => { if (skip(t)) return; const r = await exec('scene', 'return { hasTween: typeof cc.tween!=="undefined", hasVec3: typeof cc.Vec3!=="undefined", hasQuat: typeof cc.Quat!=="undefined", hasColor: typeof cc.Color!=="undefined" };'); assert.equal(r.ok, true); const v = resVal(r.body); assert.equal(v.hasVec3, true); assert.equal(v.hasTween, true); });
  });

  // ── T. sp.Skeleton deep dive — how far executeJs can drive Spine in edit mode ──
  // Finds the first live Skeleton in the scene and probes its API. Tests restore any
  // mutated property (timeScale/loop) and skip cleanly when no skeleton is present.
  describe('T sp.Skeleton deep dive', () => {
    const SKEL = 'const sc=cc.director.getScene();let sk=null,skNode=null;const st=[sc];while(st.length&&!sk){const n=st.pop();for(const c of n.components||[]){if(c&&c.constructor&&c.constructor.name==="Skeleton"){sk=c;skNode=n;break;}}for(const c of n.children||[])st.push(c);} if(!sk) return {skip:true}; ';

    it('T1 skeleton property snapshot', async (t) => { if (skip(t)) return; const r = await exec('scene', SKEL + 'return {node:skNode.name, anim:sk.animation, defaultAnim:sk.defaultAnimation, hasData:!!sk.skeletonData, timeScale:sk.timeScale, loop:sk.loop, premul:sk.premultipliedAlpha, debugBones:sk.debugBones, useTint:sk.useTint, enableBatch:sk.enableBatch, sockets:Array.isArray(sk.sockets)?sk.sockets.length:null};'); assert.equal(r.ok, true); const v = resVal(r.body); if (v.skip) { t.skip('no skeleton'); return; } assert.equal(typeof v.timeScale, 'number'); assert.equal(typeof v.loop, 'boolean'); });
    it('T2 timeScale set/read/restore', async (t) => { if (skip(t)) return; const r = await exec('scene', SKEL + 'const orig=sk.timeScale; sk.timeScale=2.5; const got=sk.timeScale; sk.timeScale=orig; return {orig, got, restored:sk.timeScale===orig};'); assert.equal(r.ok, true); const v = resVal(r.body); if (v.skip) { t.skip('no skeleton'); return; } assert.equal(v.got, 2.5); assert.equal(v.restored, true); });
    it('T3 loop toggle/read/restore', async (t) => { if (skip(t)) return; const r = await exec('scene', SKEL + 'const orig=sk.loop; sk.loop=!orig; const got=sk.loop; sk.loop=orig; return {orig, got, restored:sk.loop===orig};'); assert.equal(r.ok, true); const v = resVal(r.body); if (v.skip) { t.skip('no skeleton'); return; } assert.equal(v.restored, true); assert.notEqual(v.got, v.orig); });
    it('T4 setAnimation + getCurrent (tolerant)', async (t) => { if (skip(t)) return; const r = await exec('scene', SKEL + 'let err=null, entry=null; try{ const name=sk.defaultAnimation||sk.animation||"animation"; sk.setAnimation(0, name, true); entry=sk.getCurrent(0); }catch(e){ err=String(e.message||e); } return {err, entryOk: entry?{hasAnim:!!entry.animation, trackTime:typeof entry.trackTime==="number"?entry.trackTime:null}:null};'); assert.equal(r.ok, true); const v = resVal(r.body); if (v.skip) { t.skip('no skeleton'); return; } assert.ok(v.err === null || typeof v.err === 'string', 'no unexpected crash'); });
    it('T5 addAnimation (tolerant)', async (t) => { if (skip(t)) return; const r = await exec('scene', SKEL + 'let err=null; try{ const name=sk.defaultAnimation||sk.animation||"animation"; sk.addAnimation(0, name, true, 0.1); }catch(e){ err=String(e.message||e); } return {err};'); assert.equal(r.ok, true); const v = resVal(r.body); if (v.skip) { t.skip('no skeleton'); return; } assert.ok(v.err === null || typeof v.err === 'string'); });
    it('T6 findBone/findSlot (tolerant)', async (t) => { if (skip(t)) return; const r = await exec('scene', SKEL + 'let bone=null, slot=null, err=null; try{ bone=sk.findBone("root"); }catch(e){ err="bone:"+e.message; } try{ slot=sk.findSlot("root"); }catch(e){ err=(err?err+"; ":"")+"slot:"+e.message; } return {err, boneType:bone?(bone.name||"bone"):null, slotFound:!!slot};'); assert.equal(r.ok, true); const v = resVal(r.body); if (v.skip) { t.skip('no skeleton'); return; } assert.ok(v.err === null || typeof v.err === 'string'); });
    it('T7 setToSetupPose family (tolerant)', async (t) => { if (skip(t)) return; const r = await exec('scene', SKEL + 'let err=null; try{ sk.setToSetupPose(); sk.setBonesToSetupPose(); sk.setSlotsToSetupPose(); }catch(e){ err=String(e.message||e); } return {err};'); assert.equal(r.ok, true); const v = resVal(r.body); if (v.skip) { t.skip('no skeleton'); return; } assert.ok(v.err === null || typeof v.err === 'string'); });
    it('T8 getState returns object/null', async (t) => { if (skip(t)) return; const r = await exec('scene', SKEL + 'let state=null, err=null; try{ state=sk.getState(); }catch(e){ err=String(e.message||e); } return {err, hasState:!!state};'); assert.equal(r.ok, true); const v = resVal(r.body); if (v.skip) { t.skip('no skeleton'); return; } assert.ok(v.err === null || typeof v.err === 'string'); assert.equal(typeof v.hasState, 'boolean'); });
    it('T9 listeners register (tolerant)', async (t) => { if (skip(t)) return; const r = await exec('scene', SKEL + 'let err=null; try{ sk.setStartListener(()=>{}); sk.setEndListener(()=>{}); sk.setCompleteListener(()=>{}); sk.setEventListener(()=>{}); }catch(e){ err=String(e.message||e); } return {err};'); assert.equal(r.ok, true); const v = resVal(r.body); if (v.skip) { t.skip('no skeleton'); return; } assert.ok(v.err === null || typeof v.err === 'string'); });
    it('T10 querySockets returns array/null', async (t) => { if (skip(t)) return; const r = await exec('scene', SKEL + 'let out=null, err=null; try{ out = typeof sk.querySockets==="function" ? sk.querySockets() : null; }catch(e){ err=String(e.message||e); } return {err, isArray:Array.isArray(out), len:Array.isArray(out)?out.length:null};'); assert.equal(r.ok, true); const v = resVal(r.body); if (v.skip) { t.skip('no skeleton'); return; } assert.ok(v.err === null || typeof v.err === 'string'); });
    it('T11 skeletonData metadata (safe read)', async (t) => { if (skip(t)) return; const r = await exec('scene', SKEL + 'const sd=sk.skeletonData; if(!sd) return {hasData:false}; let animCount=null, err=null; try{ const sj=sd.skeletonJson||sd._skeletonJson; if(sj&&sj.animations) animCount=Object.keys(sj.animations).length; }catch(e){ err=String(e.message||e); } return {hasData:true, err, animCount};'); assert.equal(r.ok, true); const v = resVal(r.body); if (v.skip) { t.skip('no skeleton'); return; } assert.equal(typeof v.hasData, 'boolean'); });
  });
});
