export const GATEWAY_PROTECTED_TOOL_NAMES = [
  "animationEdit",
  "animationQuery",
  "assetBatchQuery",
  "assetGetAtPath",
  "assetGetAvailableUrl",
  "assetGetTree",
  "assetQuery",
  "assetResolvePath",
  "buildManage",
  "createButton",
  "createLabel",
  "createSprite",
  "createUiNode",
  "editorHistory",
  "editorQuery",
  "editorSelect",
  "editorViewport",
  "findNodes",
  "findNodesByAsset",
  "findNodesWithMissingAssets",
  "getPerformanceSnapshot",
  "inspectorSet",
  "materialQuery",
  "nodeBatchSet",
  "nodeClipboard",
  "nodeComponentManage",
  "nodeComponentsGet",
  "nodeCreate",
  "nodeCreatePrimitive",
  "nodeGetAtPath",
  "nodeGetAvailableComponentTypes",
  "nodeGetTree",
  "nodeOperate",
  "nodeReset",
  "projectManage",
  "propertyArrayElement",
  "runtimeGetState",
  "runtimePause",
  "runtimeResume",
  "runtimeSetTimeScale",
  "sceneGetInfo",
  "sceneManage",
  "simulateButtonClick"
] as const;

export const GATEWAY_PROTECTED_TOOLS: ReadonlySet<string> = new Set(GATEWAY_PROTECTED_TOOL_NAMES);
